apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-client
  namespace: default
spec:
  type: ClusterIP 
  selector:
    app: redis-cluster
  ports:
    - name: client
      port: 6379
      targetPort: 6379
